<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'title' => 'How To Fight',
                'author' => 'Park Tae-joon',
                'publisher' => 'PTJ Universe',
                'published_year' => 2013,
                'isbn' => '9786020495416',
                'issn' => null,
                'category' => 'Fiksi',
                'classification' => 'Novel',
                'location' => 'Rak A1-S01-K03',
                'availability_status' => 'tersedia',
                'cover_image' => 'images_covers/howtofight.jpg',
                'synopsis' => 'Novel tentang seorang pria yang menghadapi berbagai tantangan hidup dengan cara yang unik dan inspiratif. Cerita penuh humor, filosofi, dan pelajaran hidup.',
                'curator_notes' => 'Sangat menghibur dan penuh makna. Cocok untuk pembaca yang mencari cerita yang ringan tapi bermakna.',
                'stock_total' => 5,
                'stock_available' => 3,
                'is_public' => true,
            ],
            [
                'title' => 'Lookism',
                'author' => 'Park Tae-joon',
                'publisher' => 'PTJ Universe',
                'published_year' => 2014,
                'isbn' => '9786020495522',
                'issn' => null,
                'category' => 'Fiksi',
                'classification' => 'Novel',
                'location' => 'Rak B2-S02-K01',
                'availability_status' => 'tersedia',
                'cover_image' => 'images_covers/lookism.jpg',
                'synopsis' => 'Novel yang mengangkat isu diskriminasi berdasarkan penampilan fisik. Cerita tentang seorang pria yang memiliki dua tubuh dengan penampilan berbeda dan bagaimana ia menghadapi dunia yang penuh prasangka.',
                'curator_notes' => 'Sangat relevan dengan isu sosial saat ini. Membuka mata tentang pentingnya inner beauty dan self-acceptance.',
                'stock_total' => 8,
                'stock_available' => 5,
                'is_public' => true,
            ],
            [
                'title' => 'Windbreaker',
                'author' => 'Yongseok Jo',
                'publisher' => 'webtoon',
                'published_year' => 2015,
                'isbn' => '9789793062688',
                'issn' => null,
                'category' => 'Fiksi - Sastra Indonesia',
                'classification' => 'Novel Inspiratif',
                'location' => 'Rak B1-S03-K02',
                'availability_status' => 'tersedia',
                'cover_image' => 'images_covers/windbreaker.jpg',
                'synopsis' => 'Kisah dua anak Melayu yang berjuang meraih impian mereka. Dilatarbelakangi setting Belitung dengan cerita yang menyentuh hati dan menginspirasi.',
                'curator_notes' => 'Bahasa yang indah dan mengharukan. Sangat cocok untuk remaja dan orang dewasa.',
                'stock_total' => 6,
                'stock_available' => 4,
                'is_public' => true,
            ],
            [
                'title' => 'Loser Life',
                'author' => 'Park Tae-joon',
                'publisher' => 'PTJ Universe',
                'published_year' => 2016,
                'isbn' => '9789793062183',
                'issn' => null,
                'category' => 'Fiksi',
                'classification' => 'Novel',
                'location' => 'Rak B1-S03-K01',
                'availability_status' => 'tersedia',
                'cover_image' => 'images_covers/loserlife.jpg',
                'synopsis' => 'Novel yang mengisahkan perjuangan seorang pria yang dianggap "pecundang" oleh masyarakat. Cerita tentang bagaimana ia menemukan kekuatan dalam dirinya dan membuktikan bahwa kesuksesan tidak selalu diukur dari penampilan atau status sosial.',
                'curator_notes' => 'Cerita yang sangat inspiratif dan menyentuh. Cocok untuk pembaca yang merasa terpinggirkan atau sedang mencari motivasi untuk bangkit.',
                'stock_total' => 10,
                'stock_available' => 7,
                'is_public' => true,
            ],
            [
                'title' => 'Atomic Habits',
                'author' => 'James Clear',
                'publisher' => 'Penerjemah: Tim Penerjemah',
                'published_year' => 2018,
                'isbn' => '9786020516813',
                'issn' => null,
                'category' => 'Pengembangan Diri & Bisnis',
                'classification' => 'Self-help & Personal Development',
                'location' => 'Rak C1-S01-K02',
                'availability_status' => 'tersedia',
                'cover_image' => 'images_covers/atomic-habits.jpg',
                'synopsis' => 'Panduan praktis untuk membangun kebiasaan baik dan menghilangkan kebiasaan buruk melalui perubahan kecil yang efektif. Dengan contoh nyata dan sistem yang terbukti.',
                'curator_notes' => 'Buku produktivitas terbaik. Recommended untuk semua yang ingin self-improvement. Practical dan actionable.',
                'stock_total' => 7,
                'stock_available' => 3,
                'is_public' => true,
            ],
            [
                'title' => 'Sapiens: Riwayat Singkat Umat Manusia',
                'author' => 'Yuval Noah Harari',
                'publisher' => 'Penerjemah: Yul Ismanto',
                'published_year' => 2014,
                'isbn' => '9786020495430',
                'issn' => null,
                'category' => 'Sejarah & Antropologi',
                'classification' => 'Sejarah Peradaban',
                'location' => 'Rak D1-S02-K03',
                'availability_status' => 'tersedia',
                'cover_image' => 'images_covers/sapiens.jpg',
                'synopsis' => 'Sejarah manusia dari era prasejarah hingga era modern. Mengeksplorasi bagaimana manusia berkembang dan membentuk dunia yang kita kenal hari ini.',
                'curator_notes' => 'Perspektif unik tentang sejarah manusia. Merangsang pemikiran kritis. Cocok untuk yang ingin memahami big picture of humanity.',
                'stock_total' => 4,
                'stock_available' => 2,
                'is_public' => true,
            ],
            [
                'title' => 'Sebuah Seni untuk Bersikap Bodo Amat',
                'author' => 'Mark Manson',
                'publisher' => 'Gramedia Pustaka Utama',
                'published_year' => 2016,
                'isbn' => '9786020495409',
                'issn' => null,
                'category' => 'Pengembangan Diri & Filosofi',
                'classification' => 'Self-help',
                'location' => 'Rak C2-S01-K01',
                'availability_status' => 'tersedia',
                'cover_image' => 'images_covers/don-t-give-a-f.jpg',
                'synopsis' => 'Panduan kejujuran tentang cara menjalani hidup dengan fokus pada hal yang benar-benar penting. Lepaskan hal yang tidak perlu dan fokuslah pada makna sejati.',
                'curator_notes' => 'Berbahasa casual dan menarik. Filosofi hidup modern yang relevan. Refreshing dan membebaskan.',
                'stock_total' => 5,
                'stock_available' => 4,
                'is_public' => true,
            ],
            [
                'title' => 'Pulang Pergi',
                'author' => 'Perjalanan Jakarta-Bandung',
                'publisher' => 'Transmedia Pustaka',
                'published_year' => 2019,
                'isbn' => '9786020495478',
                'issn' => null,
                'category' => 'Fiksi - Perjalanan',
                'classification' => 'Novel Urban Drama',
                'location' => 'Rak B3-S01-K02',
                'availability_status' => 'tersedia',
                'cover_image' => 'images_covers/pulang-pergi.jpg',
                'synopsis' => 'Cerita tentang seorang wanita muda yang melakukan perjalanan rutin antara Jakarta dan Bandung sambil mencari jati diri dan tujuan hidupnya.',
                'curator_notes' => 'Contemporary fiction yang relatable. Setting urban dan modern. Cocok untuk pembaca millennial.',
                'stock_total' => 3,
                'stock_available' => 2,
                'is_public' => true,
            ],
            [
                'title' => 'Thinking, Fast and Slow',
                'author' => 'Daniel Kahneman',
                'publisher' => 'Penerjemah: Joga Bendesa',
                'published_year' => 2011,
                'isbn' => '9786020495546',
                'issn' => null,
                'category' => 'Psikologi & Sains Kognitif',
                'classification' => 'Behavioral Economics',
                'location' => 'Rak E1-S02-K01',
                'availability_status' => 'tersedia',
                'cover_image' => 'images_covers/thinking-fast-slow.jpg',
                'synopsis' => 'Eksplorasi mendalam tentang cara pikiran manusia bekerja. Menjelaskan cognitive biases dan bagaimana kita membuat keputusan dalam kehidupan sehari-hari.',
                'curator_notes' => 'Karya pemenang Nobel Prize. Kompleks tapi enlightening. Untuk yang serius tentang psychology of mind.',
                'stock_total' => 4,
                'stock_available' => 3,
                'is_public' => true,
            ],
            [
                'title' => 'Indonesia Raya: Nasionalisme dan Revolusi',
                'author' => 'Ricklefs, M.C.',
                'publisher' => 'Gramedia Pustaka Utama',
                'published_year' => 2008,
                'isbn' => '9786020495485',
                'issn' => null,
                'category' => 'Sejarah Indonesia',
                'classification' => 'Modern Indonesian History',
                'location' => 'Rak D2-S03-K02',
                'availability_status' => 'tersedia',
                'cover_image' => 'images_covers/indonesia-raya.jpg',
                'synopsis' => 'Analisis komprehensif tentang perkembangan nasionalisme Indonesia dan perjalanan revolusi menuju kemerdekaan. Perspektif historis yang objektif.',
                'curator_notes' => 'Academic reference yang kredibel. Untuk researcher dan yang ingin deep understanding sejarah Indonesia.',
                'stock_total' => 2,
                'stock_available' => 2,
                'is_public' => true,
            ],
        ];

        foreach ($books as $book) {
            Book::create($book);
        }
    }
}
